export const HOME = '/'
export const PAY_BILL = '/elite-bank-app/pay-bills'
export const MANAGE_BILL = '/elite-bank-app/manage-bills'
export const TRANSFER = '/elite-bank-app/transfer-funds'
export const INVEST = '/elite-bank-app/investments'
export const INVESTNEW = '/elite-bank-app/investments/new'

export const BENEFICIARIES = '/elite-bank-app/beneficiaries'
export const TRANSACTION_HISTORY = '/elite-bank-app/transaction-history'
export const TRANSACTION_STATMENT = '/elite-bank-app/account-statement'

export const ACCOUNT_SETTINGS = '/elite-bank-app/settings/account-setting'
export const HELP = '/elite-bank-app/settings/help'
export const LEGAL = '/elite-bank-app/settings/legal'
export const PROFILE = '/elite-bank-app/settings/profile'
